automation:
  - id: timeskifte
    alias: Timessskifte
    description: ''
    trigger:
      - platform: time
        at: "00:59:00"
      - platform: time
        at: "01:59:00"
      - platform: time
        at: "02:59:00"
      - platform: time
        at: "03:59:00"
      - platform: time
        at: "04:59:00"
      - platform: time
        at: "05:59:00"
      - platform: time
        at: "06:59:00"
      - platform: time
        at: "07:59:00"
      - platform: time
        at: "08:59:00"
      - platform: time
        at: "09:59:00"
      - platform: time
        at: "10:59:00"
      - platform: time
        at: "11:59:00"
      - platform: time
        at: "12:59:00"
      - platform: time
        at: "13:59:00"
      - platform: time
        at: "14:59:00"
      - platform: time
        at: "15:59:00"
      - platform: time
        at: "16:59:00"
      - platform: time
        at: "17:59:00"
      - platform: time
        at: "18:59:00"
      - platform: time
        at: "19:59:00"
      - platform: time
        at: "20:59:00"
      - platform: time
        at: "21:59:00"
      - platform: time
        at: "22:59:00"
      - platform: time
        at: "23:59:00"
    condition:
    action:
    - alias: ''
      data_template:
        value: '{{ state_attr(''sensor.real_time_consumption_hegglia_5'',
          ''lastMeterConsumption'') }}'
        entity_id: input_number.consumption_lasthour
      service: input_number.set_value

  - id: manedsskifte
    alias: Månedsskifte
    description: ''
    trigger:
    - at: 0:30:00
      platform: time
    condition:
    - condition: template
      value_template: '{{ now().day == 1 }}'
    action:
    - alias: ''
      data_template:
        entity_id: input_number.consumption_lastmonth
        value: '{{ (state_attr(''sensor.real_time_consumption_hegglia_5'',
          ''lastMeterConsumption'') - float(states(''input_number.consumption_startofmonth'')))
          | round(1) }}'
      service: input_number.set_value
    - alias: ''
      data_template:
        value: '{{ state_attr(''sensor.real_time_consumption_hegglia_5'',
          ''lastMeterConsumption'') }}'
        entity_id: input_number.consumption_startofmonth
      service: input_number.set_value
  - id: aarsskifte
    alias: Årsskifte
    description: ''
    trigger:
    - at: 0:30:00
      platform: time
    condition:
    - condition: template
      value_template: '{{ now().day == 1 and now().month == 1 }}'
    action:
    - alias: ''
      data_template:
        value: '{{ state_attr(''sensor.real_time_consumption_hegglia_5'',
          ''lastMeterConsumption'') }}'
        entity_id: input_number.consumption_startofyear
      service: input_number.set_value
  - id: dagskifte
    alias: Dagskifte
    description: ''
    trigger:
    - at: 0:05:00
      platform: time
    action:
    - alias: ''
      data_template:
        entity_id: input_number.consumption_lastday
        value: '{{ (state_attr(''sensor.real_time_consumption_hegglia_5'',
          ''lastMeterConsumption'') - float(states(''input_number.consumption_startofday'')))
          | round(1) }}'
      service: input_number.set_value
    - alias: ''
      data_template:
        entity_id: input_number.consumption_startofday
        value: '{{ state_attr(''sensor.real_time_consumption_hegglia_5'',
          ''lastMeterConsumption'') }}'
      service: input_number.set_value

  - id: dagskifte_kostnad
    alias: Dagskifte - Kostnad
    description: ''
    trigger:
      - platform: time
        at: "23:59:00"
    action:
    - alias: ''
      data_template:
        entity_id: input_number.cost_lastday
        value: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'accumulatedCost') }}"
      service: input_number.set_value

  - id: ukeskifte
    alias: Ukeskifte
    description: ''
    trigger:
    - at: 0:05:00
      platform: time
    condition:
      - condition: time
        weekday:
          - mon
    action:
    - alias: ''
      data_template:
        entity_id: input_number.consumption_lastweek
        value: '{{ (state_attr(''sensor.real_time_consumption_hegglia_5'',
          ''lastMeterConsumption'') - float(states(''input_number.consumption_startofweek'')))
          | round(1) }}'
      service: input_number.set_value
    - alias: ''
      data_template:
        entity_id: input_number.consumption_startofweek
        value: '{{ state_attr(''sensor.real_time_consumption_hegglia_5'',
          ''lastMeterConsumption'') }}'
      service: input_number.set_value

sensor:
  - platform: template
    sensors:    
      strompris:
        friendly_name: "Strømpris nå"
        unit_of_measurement: 'Øre'
        value_template: '{{ (states.sensor.electricity_price_hegglia_5.state | multiply(100)) + (states.input_number.nettleie.state | multiply(100) ) | round(1) }}'

      strompris_gjennomsnitt:
        friendly_name: "Strømpris - Gj.snitt"
        unit_of_measurement: 'Øre'
        value_template: "{{ (state_attr('sensor.electricity_price_hegglia_5', 'avg_price') | multiply(100)) + (states.input_number.nettleie.state | multiply(100)) | round(1) }}"

      strompris_max:
        friendly_name: "Strømpris - Høyest"
        unit_of_measurement: 'Øre'
        value_template: "{{ (state_attr('sensor.electricity_price_hegglia_5', 'max_price') | multiply(100)) +  (states.input_number.nettleie.state ) | multiply(100) | round(1) }}"

      strompris_lavest:
        friendly_name: "Strømpris - Lavest"
        unit_of_measurement: 'Øre'
        value_template: "{{ (state_attr('sensor.electricity_price_hegglia_5', 'min_price') | multiply(100)) +  (states.input_number.nettleie.state | multiply(100) ) | round(1) }}"

      stromleverandor:
        friendly_name: "Strømleverandør"
        value_template: "{{ state_attr('sensor.electricity_price_hegglia_5', 'grid_company') }}"

      strompris_niva:
        friendly_name: "Strømpris nivå"
        value_template: "{{ state_attr('sensor.electricity_price_hegglia_5', 'price_level') }}"

      strom_estimert:
        friendly_name: "Estimert årlig forbruk"
        unit_of_measurement: 'kWh'
        value_template: "{{ state_attr('sensor.electricity_price_hegglia_5', 'estimated_annual_consumption') }}"

      ams_spenning_l1:
        friendly_name: "Spenning L1"
        unit_of_measurement: 'V'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'voltagePhase1') }}"

      ams_spenning_l2:
        friendly_name: "Spenning L2"
        unit_of_measurement: 'V'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'voltagePhase2') }}"

      ams_spenning_l3:
        friendly_name: "Spenning L3"
        unit_of_measurement: 'V'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'voltagePhase3') }}"

      ams_strom_l1:
        friendly_name: "Strøm L1"
        unit_of_measurement: 'A'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'currentL1') }}"

      ams_strom_l2:
        friendly_name: "Strøm L2"
        unit_of_measurement: 'A'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'currentL2') }}"

      ams_strom_l3:
        friendly_name: "Strøm L3"
        unit_of_measurement: 'A'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'currentL3') }}"

      ams_min_trekk:
        friendly_name: "Laveste effektforbruk"
        unit_of_measurement: 'W'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'minPower') }}"

      ams_hoy_trekk:
        friendly_name: "Høyeste effektforbruk"
        unit_of_measurement: 'W'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'maxPower') }}"

      ams_gj_trekk:
        friendly_name: "Gj.snitt effektforbruk"
        unit_of_measurement: 'W'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'averagePower') }}"

      ams_akk_forbruk:
        friendly_name: "Dagens forbruk"
        unit_of_measurement: 'kWh'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'accumulatedConsumption') | round(2) }}"

      ams_akk_kostnad:
        friendly_name: "Kostnad i dag"
        unit_of_measurement: 'kWh'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'accumulatedCost') | round(2)}}"

      ams_signal:
        friendly_name: "Signalstyrke"
        unit_of_measurement: 'dB'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'signalStrength') }}"

      ams_malerstand:
        friendly_name: "Målerstand"
        unit_of_measurement: 'kWh'
        value_template: "{{ state_attr('sensor.real_time_consumption_hegglia_5', 'lastMeterConsumption') | round(0) }}"

      consumption_thisyear:
        friendly_name: "Forbruk dette år"
        unit_of_measurement: 'kWh'
        value_template: "{{ (state_attr('sensor.real_time_consumption_hegglia_5', 'lastMeterConsumption') - float(states('input_number.consumption_startofyear'))) | round(1) }}"

      consumption_thismonth:
        friendly_name: "Forbruk denne måned"
        unit_of_measurement: 'kWh'
        value_template: "{{ (state_attr('sensor.real_time_consumption_hegglia_5', 'lastMeterConsumption') - float(states('input_number.consumption_startofmonth'))) | round(1) }}"

      consumption_lastmonth:
        friendly_name: "Forbruk forrige uke"
        unit_of_measurement: 'kWh'
        value_template: "{{ float(states('input_number.consumption_lastmonth')) }}"

      consumption_thisweek:
        friendly_name: "Forbruk denne uken"
        unit_of_measurement: 'kWh'
        value_template: "{{ (state_attr('sensor.real_time_consumption_hegglia_5', 'lastMeterConsumption') - float(states('input_number.consumption_startofweek'))) | round(1) }}"

      consumption_lastweek:
        friendly_name: "Forbruk forrige uke"
        unit_of_measurement: 'kWh'
        value_template: "{{ float(states('input_number.consumption_lastweek')) }}"

      consumption_thisday:
        friendly_name: "Forbruk i dag"
        unit_of_measurement: 'kWh'
        value_template: "{{ (state_attr('sensor.real_time_consumption_hegglia_5', 'lastMeterConsumption') - float(states('input_number.consumption_startofday'))) | round(2) }}"

      consumption_lastday:
        friendly_name: "Forbruk i går"
        unit_of_measurement: 'kWh'
        value_template: "{{ float(states('input_number.consumption_lastday')) }}"

      cost_lastday:
        friendly_name: "Kostnad i går"
        unit_of_measurement: 'Kr.'
        value_template: "{{ float(states('input_number.cost_lastday')) | round(2) }}"

      consumption_lasthour:
        friendly_name: "Forbruk forrige time"
        unit_of_measurement: 'kWh'
        value_template: "{{ (state_attr('sensor.real_time_consumption_hegglia_5', 'lastMeterConsumption')) - float(states('input_number.consumption_lasthour')) | round(2) }}"

input_number:
  consumption_startofyear:
    name: Målerstand start på år
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  consumption_startofmonth:
    name: Målerstand start på måned
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  consumption_lastmonth:
    name: Målerstand forrige måned
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  consumption_startofweek:
    name: Målerstand start på uke
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  consumption_lastweek:
    name: Forbruk forrige uke
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  consumption_startofday:
    name: Målerstand start på dag
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  consumption_lastday:
    name: Forbruk forrige dag
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  cost_lastday:
    name: Kostnad forrige dag
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  consumption_lasthour:
    name: Forbruk forrige time
    max: 999999999
    min: 0
    step: 0.1
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:counter
  nettleie:
    name: Nettleie
    min: 0
    max: 2
    step: 0.001
    mode: box
    unit_of_measurement: NOK/kWh

utility_meter:
  oppvarming_daglig:
    source: sensor.forbruk_oppvarming
    cycle: daily

  oppvarming_uke:
    source: sensor.forbruk_oppvarming
    cycle: weekly

  oppvarming_mnd:
    source: sensor.forbruk_oppvarming
    cycle: monthly
