- id: '1557297178655'
  alias: Dagens oppdatering
  trigger:
  - at: 09:00:00
    platform: time
  condition: []
  action:
  - data:
      message: Det er {{states('sensor.ute_sensor_temperatur')}} grader
        ute. Søppel hentes om {{states('sensor.kalender_soppel_igjen')}} dager.
      title: Dagens oppdatering
    service: notify.mobile_app_sm_g988b
    
- id: '1561241831216'
  alias: Soveromsvindu
  trigger:
  - entity_id: binary_sensor.noen_hjemme
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.soverom_vindu
    state: 'on'
  action:
  - data:
      message: Soveromsvinduet er åpent!
    service: notify.mobile_app_clt_l29
  - data:
      message: Soveromsvinduet er åpent!
    service: notify.mobile_app_sm_g988b

- id: '1567144824959'
  alias: Støvsuger feil
  trigger:
  - entity_id: vacuum.xiaomi_vacuum_cleaner
    platform: state
    to: error
  condition: []
  action:
  - data:
      message: Jeg kommer meg ikke videre, fint om du kan sjekke til meg når du kommer
        hjem. Hilsen, din støvsuger.
    service: notify.mobile_app_sm_g988b
  - data:
      message: Jeg kommer meg ikke videre, fint om du kan sjekke til meg når du kommer
        hjem. Hilsen, din støvsuger.
    service: notify.mobile_app_clt_l29

- id: ringeklokke
  alias: Ringeklokke varsel
  trigger:
  - entity_id: binary_sensor.postkasse
    platform: state
    from: 'on'
    to: 'off'
  condition:
    condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr(''automation.ringeklokke'',
      ''last_triggered'') | default(0)) | int > 5)}}'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.inngangsdor
      filename: /config/www/doorbell.jpg
  - service: notify.mobile_app_sm_g988b
    data:
      message: Det ringer på!
      data:
        image: https://u7kv25oww0snuspceopf9kr1cjhwcvi8.ui.nabu.casa/local/doorbell.jpg
  - service: notify.mobile_app_clt_l29
    data:
      message: Det ringer på!
      data:
        image: https://u7kv25oww0snuspceopf9kr1cjhwcvi8.ui.nabu.casa/local/doorbell.jpg
