automation:
- alias: Utelys - Lys på ved solnedgang
  trigger:
  - platform: state
    entity_id: input_boolean.utebelysning
    from: "off"
    to: "on"
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.utebelysning
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel_4
      transition: 1
      brightness_pct: 90
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel_3
      transition: 1
      brightness_pct: 90
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel_2
      transition: 1
      brightness_pct: 90
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel_1
      transition: 1
      brightness_pct: 90
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.garasje_ved_port
      transition: 1
      brightness_pct: 80
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.garasje_soppelskur_venstre
      transition: 1
      brightness_pct: 70
  - service: light.turn_on
    data:
      entity_id: light.garasje_soppelskur_hoyre
      transition: 1
      brightness_pct: 70
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.husvegg_ved_vaskerom
      transition: 1
      brightness_pct: 80
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.husvegg_ved_inngangsdor
      transition: 1
      brightness_pct: 80
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.veranda_over_sofa_1
      transition: 1
      brightness_pct: 65
      color_temp: 375
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.veranda_over_sofa_2
      transition: 1
      brightness_pct: 65
      color_temp: 375
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.veranda_ved_hagedor
      transition: 1
      brightness_pct: 65
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.hage_trapp
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.hage_1
      transition: 1
      brightness_pct: 95
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.hage_2
      transition: 1
      brightness_pct: 95
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.hage_3
      transition: 1
      brightness_pct: 95
  - service: light.turn_on
    data:
      entity_id: light.hage
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel
  - service: light.turn_on
    data:
      entity_id: light.garasje
  - service: light.turn_on
    data:
      entity_id: light.husvegg


- alias: Utelys - Lys av ved soloppgang
  trigger:
  - platform: state
    entity_id: input_boolean.utebelysning
    from: "on"
    to: "off"
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.utebelysning
  - service: light.turn_off
    data:
      entity_id: light.innkjorsel_4
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.innkjorsel_3
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.innkjorsel_2
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.innkjorsel_1
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.garasje_ved_port
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.garasje_soppelskur_venstre
      transition: 1
  - service: light.turn_off
    data:
      entity_id: light.garasje_soppelskur_hoyre
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.husvegg_ved_vaskerom
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.husvegg_ved_inngangsdor
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.veranda_over_sofa_1
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.veranda_over_sofa_2
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.veranda_ved_hagedor
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.hage_trapp
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.hage_1
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.hage_2
      transition: 1
  - delay: 
      milliseconds: 300
  - service: light.turn_off
    data:
      entity_id: light.hage_3
      transition: 1
  - service: light.turn_off
    data:
      entity_id: light.hage
  - service: light.turn_off
    data:
      entity_id: light.innkjorsel
  - service: light.turn_off
    data:
      entity_id: light.garasje
  - service: light.turn_off
    data:
      entity_id: light.husvegg

- alias: Lys av i stuer hvis ingen hjemme
  trigger:
  - at: '23:05:35'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.noen_hjemme
    state: 'off'
  action:
  - service: light.turn_off
    data:
      entity: light.spisestue
  - service: light.turn_off
    data:
      entity: light.gang
  - service: light.turn_off
    data:
      entity: light.kjokken

- alias: Lys på i stuer hvis ingen hjemme
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: binary_sensor.noen_hjemme
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity: light.spisestue
      transition: 1
      brightness_pct: 50
  - service: light.turn_on
    data:
      entity: light.gang
      transition: 1
      brightness_pct: 50

- alias: Lystenning
  trigger:
  - platform: state
    entity_id: input_boolean.julebelysning
    from: "off"
    to: "on"
  condition: []
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.utebelysning
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel_4
      transition: 1
      brightness_pct: 90
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel_3
      transition: 1
      brightness_pct: 90
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel_2
      transition: 1
      brightness_pct: 90
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel_1
      transition: 1
      brightness_pct: 90
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.garasje_ved_port
      transition: 1
      brightness_pct: 80
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.garasje_soppelskur_venstre
      transition: 1
      brightness_pct: 70
  - service: light.turn_on
    data:
      entity_id: light.garasje_soppelskur_hoyre
      transition: 1
      brightness_pct: 70
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.husvegg_ved_vaskerom
      transition: 1
      brightness_pct: 80
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.husvegg_ved_inngangsdor
      transition: 1
      brightness_pct: 80
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: switch.julelys_innkjorsel_bryter
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.veranda_over_sofa_1
      transition: 1
      brightness_pct: 65
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.veranda_over_sofa_2
      transition: 1
      brightness_pct: 65
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.veranda_ved_hagedor
      transition: 1
      brightness_pct: 65
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.hage_trapp
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.hage_1
      transition: 1
      brightness_pct: 95
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.hage_2
      transition: 1
      brightness_pct: 95
  - delay: 
      milliseconds: 300
  - service: light.turn_on
    data:
      entity_id: light.hage_3
      transition: 1
      brightness_pct: 95
  - service: light.turn_on
    data:
      entity_id: light.hage
  - service: light.turn_on
    data:
      entity_id: light.innkjorsel
  - service: light.turn_on
    data:
      entity_id: light.garasje
  - service: light.turn_on
    data:
      entity_id: light.husvegg


- alias: Julebelysning innkjørsel - Varsel om endring i strømtrekk
  trigger:
  - below: 25
    entity_id: sensor.julelys_innkjorsel_power_3
    platform: numeric_state
    for: '0:00:10'
  - above: 35
    entity_id: sensor.julelys_innkjorsel_power_3
    platform: numeric_state
    for: '0:00:10'
  condition:
  - condition: state
    entity_id: switch.julelys_innkjorsel_bryter
    state: 'on'
  action:
  - service: tts.google_say
    entity_id: media_player.home_spisestue, media_player.home_kjellerstue
    data_template:
      message: Endring i strømtrekk på julebelysning i innkjørsel, slår av lys.
      cache: false
      language: 'no'
  - service: notify.mobile_app_sm_g988b
    data:
      title: 'Endring i strømtrekk'
      message: "Strømtrekket på juletrebelysningen i innkjørsel har endret seg og er nå {{states('sensor.julelys_innkjorsel_power_3')}}W, slår av lysene."
  - service: switch.turn_off
    entity_id: switch.julelys_innkjorsel_bryter

input_boolean:
  utebelysning:
    name: Utebelysning sekvens
    icon: mdi:lightbulb
  julebelysning:
    name: Julebelysning sekvens
    icon: mdi:lightbulb

light:
  - platform: group
    name: altinne
    entities:
      - light.gang
      - light.garderobe
      - light.kjellerstue
      - light.kjokken
      - light.spisestue
      - light.soverom
  - platform: group
    name: oppe
    entities:
      - light.kjokken
      - light.spisestue
  - platform: group
    name: nede
    entities:
      - light.gang
      - light.garderobe
      - light.kjellerstue
