automation:
  - alias: Yttergang - Åpne garasjeport via bryter
    trigger:
    - event_data:
        entity_id: zwave.yttergang
        scene_id: 1
        scene_data: 0
      event_type: zwave.scene_activated
      platform: event
    condition: []
    action:
      - service: cover.open_cover
        data:
          entity_id: cover.garage_door
      - service: media_player.volume_set
        data:
          entity_id: media_player.home_kjellerstue
          volume_level: '0.5'
      - service: tts.google_say
        entity_id: media_player.home_kjellerstue
        data_template:
          message: Åpner garasjeport
          cache: false
          language: 'no'

  - alias: Yttergang - Lukk garasjeport via bryter
    trigger:
    - event_data:
        entity_id: zwave.yttergang
        scene_id: 3
        scene_data: 0
      event_type: zwave.scene_activated
      platform: event
    condition: []
    action:
      - service: cover.close_cover
        data:
          entity_id: cover.garage_door
      - service: media_player.volume_set
        data:
          entity_id: media_player.home_kjellerstue
          volume_level: '0.5'
      - service: tts.google_say
        entity_id: media_player.home_kjellerstue
        data_template:
          message: Lukker garasjeport
          cache: false
          language: 'no'

  - id: garasje_åpnet
    alias: 'Garasjeport åpnet'
    trigger:
      - platform: state
        entity_id: cover.garage_door
        to: 'open'
    condition:
      condition: state
      entity_id: cover.garage_door
      state: 'open'
    action:
      - service: timer.start
        entity_id: timer.garasjeport

  - id: garasje_lukket
    alias: 'Garasjeport lukket'
    trigger:
      - platform: state
        entity_id: cover.garage_door
        to: 'closed'
    action:
      - service: timer.cancel
        entity_id:  timer.garasjeport

  - id: garasje_varsel
    alias: 'Garasjeport varsel'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.garasjeport
    condition:
      condition: state
      entity_id: cover.garage_door
      state: 'open'
    action:
      - service: tts.google_say
        entity_id: media_player.home_spisestue, media_player.kjokken, media_player.home_kjellerstue
        data_template:
          message: Garasjeporten er enda åpen
          cache: false
          language: 'no'
      - service: notify.mobile_app_sm_g988b
        data:
          message: "Garasjeporten er enda åpen!"
          data:
            actions:
              - action: "lukkport"
                title: "Lukk port"
      - service: timer.start
        entity_id: timer.garasjeport
  - alias: Lukk port
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: lukkport
    action:
      - service: cover.close_cover
        entity_id: cover.garage_door

  - id: garasjeport_varsel_ingen_hjemme
    alias: 'Garasjeport varsel - Ingen hjemme'
    trigger:
      - platform: state
        entity_id: binary_sensor.noen_hjemme
        to: 'off'
        for: 00:01:00
    condition:
      condition: state
      entity_id: cover.garage_door
      state: 'open'
    action:
      - data:
          message: Garasjeport er åpen selvom ingen er hjemme!
        service: notify.mobile_app_clt_l29
      - data:
          message: Garasjeport er åpen selvom ingen er hjemme!
        service: notify.mobile_app_sm_g988b

  - id: '1597849634000'
    alias: Garasjelys - Av
    description: Garasjelys av ved lukking av port
    trigger:
    - entity_id: sensor.garasje_port
      for: '2'
      from: '22'
      platform: state
      to: '23'
    condition: []
    action:
    - device_id: 7c25b47d13ad4c928cd174d5390f052d
      domain: switch
      entity_id: switch.garasjelys_bryter
      type: turn_off
    mode: single

  - id: '1597849559523'
    alias: Garasjelys - På
    description: Garasjelys på ved åpning av port
    trigger:
    - entity_id: sensor.garasje_port
      from: '23'
      platform: state
      to: '22'
    condition: []
    action:
    - device_id: 7c25b47d13ad4c928cd174d5390f052d
      domain: switch
      entity_id: switch.garasjelys_bryter
      type: turn_on
    mode: single

cover:
  - platform: template
    covers:
      garage_door:
        friendly_name: "Garasjeport"
        value_template: "{{ states('sensor.garasje_port')|float < 23 }}"
        open_cover:
          service: script.open_garage_door
        close_cover:
          service: script.close_garage_door
        stop_cover:
          service: script.stop_garage_door
        icon_template: >-
          {% if is_state('sensor.garasje_port', '23') %}
          mdi:garage
          {% else %}
          mdi:garage-open
          {% endif %}

script:
  open_garage_door:
    sequence:
    - data:
        entity_id: switch.garasje_portapner
      service: switch.turn_on
    - data:
        message: Garasjeport åpnet via smarthus
      service: notify.mobile_app_clt_l29
    - data:
        message: Garasjeport åpnet via smarthus
      service: notify.mobile_app_sm_g988b
  close_garage_door:
    sequence:
    - data:
        entity_id: switch.garasje_portapner
      service: switch.turn_on
  stop_garage_door:
    sequence:
    - data:
        entity_id: switch.garasje_portapner
      service: switch.turn_on

timer:    
  garasjeport:
    duration: '00:30:00'
