automation:
- id: velkomst tidstaker start
  alias: 'velkomst tidstaker start'
  trigger:
    - platform: state
      entity_id: binary_sensor.noen_hjemme
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.noen_hjemme
    state: 'on'
  action:
  - service: timer.start
    data:
      entity_id: timer.inngangsdor
  - service: input_boolean.turn_on
    entity_id: input_boolean.inngangsdor_tid

- id: velkomst tidstaker ferdig
  alias: 'velkomst tidstaker ferdig'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.inngangsdor
  action:
    - service: timer.cancel
      data:
        entity_id:  timer.inngangsdor
    - service: input_boolean.turn_off
      entity_id: input_boolean.inngangsdor_tid

- alias: Velkomst
  trigger:
  - from: 'off'
    to: 'on'
    entity_id: binary_sensor.gang_inngangsdor
    platform: state
  condition:
  - condition: state
    entity_id: input_boolean.inngangsdor_tid
    state: 'on'
  action:
  - data:
      entity_id: light.gang
    service: light.turn_on
  - data:
      entity_id: light.spisestue
    service: light.turn_on
  - data:
      entity_id: light.kjokken
    service: light.turn_on
  - service: switch.turn_on
    data:
      entity_id: switch.hovedkran
  - service: tts.google_say
    entity_id: media_player.home_kjellerstue
    data_template:
      message: Velkommen hjem
      cache: false
      language: 'no'
  - service: timer.cancel
    data:
      entity_id:  timer.inngangsdor
  - service: input_boolean.turn_off
    entity_id: input_boolean.inngangsdor_tid

- alias: Yttergang - Bortemodus
  trigger:
  - event_data:
      entity_id: zwave.yttergang
      scene_id: 4
      scene_data: 2
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
    - service: light.turn_off
      data:
        entity_id: light.gang
    - service: light.turn_off
      data:
        entity_id: light.spisestue
    - service: light.turn_off
      data:
        entity_id: light.kjokken
    - service: light.turn_off
      data:
        entity_id: light.kjellerstue
    - service: switch.turn_off
      data:
        entity_id: switch.vaskerom_vaskemaskin
    - service: switch.turn_off
      data:
        entity_id: switch.vaskerom_torketrommel
    - service: switch.turn_off
      data:
        entity_id: switch.hovedkran
    - service: switch.turn_off
      data:
        entity_id: switch.kjokken_stikk_venstre
    - service: media_player.volume_set
      data:
        entity_id: media_player.home_kjellerstue
        volume_level: '0.5'
    - service: tts.google_say
      entity_id: media_player.home_kjellerstue
      data_template:
        message: Slår alt av, god tur!
        cache: false
        language: 'no'

- alias: Yttergang - Kort bortemodus
  trigger:
  - event_data:
      entity_id: zwave.yttergang
      scene_id: 4
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
    - service: light.turn_off
      data:
        entity_id: light.gang
    - service: light.turn_off
      data:
        entity_id: light.spisestue
    - service: light.turn_off
      data:
        entity_id: light.kjokken
    - service: light.turn_off
      data:
        entity_id: light.kjellerstue
    - service: switch.turn_off
      data:
        entity_id: switch.hovedkran
    - service: media_player.volume_set
      data:
        entity_id: media_player.home_kjellerstue
        volume_level: '0.5'
    - service: tts.google_say
      entity_id: media_player.home_kjellerstue
      data_template:
        message: Hadet bra
        cache: false
        language: 'no'

- alias: Yttergang - Normalmodus
  trigger:
  - event_data:
      entity_id: zwave.yttergang
      scene_id: 2
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
  condition: []
  action:
    - service: light.turn_on
      data:
        entity_id: light.gang
    - service: light.turn_on
      data:
        entity_id: light.kjokken
    - service: light.turn_on
      data:
        entity_id: light.spisestue
    - service: switch.turn_on
      data:
        entity_id: switch.vaskerom_vaskemaskin
    - service: switch.turn_on
      data:
        entity_id: switch.vaskerom_torketrommel
    - service: switch.turn_on
      data:
        entity_id: switch.hovedkran
    - service: media_player.volume_set
      data:
        entity_id: media_player.home_kjellerstue
        volume_level: '0.5'
    - service: tts.google_say
      entity_id: media_player.home_kjellerstue
      data_template:
        message: Velkommen hjem!
        cache: false
        language: 'no'

input_boolean:
  inngangsdor_tid:
    name: Velkomst tid
    initial: off

timer:
  inngangsdor:
    duration: '00:10:00'
